### ISSUE TITLE
Remove all the http specific code and only parse strings or streams

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/clj-cctray#11]
@cowley05 @joejag

I was thinking, should loading of the cctray xml file be done by this library?

We could just take either a stream or a string that is the loaded xml file and then pass it into a map. This would make this library simpler as it would no longer have to worry about issues with things like https or timeouts. This would also allow developers to use their libs of choice for actually loading the xml from files or urls.

Thoughts?

**Comment by GentlemanHal** [comment]
Ok cool, I'm going to change this issue to remove the http stuff.

**Comment by GentlemanHal** [comment]
@joejag Rather than adding an example to the readme I'll update Nevergreen and link to that as an example of this library being used in a real project.

**Comment by joejag** [comment]
It appears we can communicate in Github via selfies. So @GentlemanHal my response is:

![selfie-0](http://i.imgur.com/gZlVrs5.png)

**Comment by GentlemanHal** [comment]
@joejag Haha, right-o! I'm going to close this then as I've removed the reader namespace with my last commit.
