### ISSUE TITLE
Jenkins - Multibranch pipelines show branch name for the project in cc.xml

### ISSUE THREAD

**Issue by darrenhaken** [build-canaries/clj-cctray#17]
When using the Jenkins multiple project pipeline the project name maps to the branch.
This means that you can end up with multiple builds with the same name i.e. master.

For multibranch pipelines we could parse the Git URL and add that to the name as an option to fix.

**Comment by darrenhaken** [comment]
`<Projects>
  <Project activity="Sleeping" lastBuildStatus="Success" lastBuildLabel="1" webUrl="http://hostname/view/viewName/job/project1/job/master/" name="master" lastBuildTime="2017-03-20T14:41:47Z"/>
  <Project activity="Sleeping" lastBuildStatus="Success" lastBuildLabel="1" webUrl="http://hostname/view/viewName/job/project2/job/master/" name="master" lastBuildTime="2017-03-20T15:07:00Z"/>
</Projects>`

**Comment by GentlemanHal** [comment]
Do you mean this plugin?

https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Multibranch+Plugin

If so could you raise an issue directly with them as that would be better than us creating a specific workaround.

If they don't respond or refuse to fix, we could do as you suggest and parse the name out of the URL. I'm not happy about that as it feels a little flakey, but I guess it's better than every project being called master!

**Comment by darrenhaken** [comment]
@GentlemanHal yeah I'll do that and you're right it certainly shouldn't be us making the work around.
