### ISSUE TITLE
Update to CircleCI 2.0

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/clj-cctray#19]
CircleCI 1.0 is closing down so we need to upgrade.

https://circleci.com/blog/sunsetting-1-0/

We should also take this opportunity to create a better pipeline that can push releases to GitHub and Clojars.

**Comment by cowley05** [comment]
ive updated the yaml to be the same folder structure as in nevergreen and updated it to version 2. Theres a small hack, I couldnt figure out on circleci how to upload an artifact with a wildcard eg. ./target/clj-cctray-*.jar

This doesnt work neither does ./target/*.jar so insteadI created a new folder and moved it there, then uploaded that whole folder as an artifact which works fine.

We still need to release to GH and Clojars though.

**Comment by GentlemanHal** [comment]
I've added steps to release to GH and Clojars.

We still need to update the API docs, but I'm not sure how easy that'll be as it requires pushing to the `gh-pages` branch.

**Comment by GentlemanHal** [comment]
I've added a new issue, #21, to cover this so I'm going to close this issue.
